---
title: "Summary G2F Validation"
output: pdf_document
---

```{r setup, echo=FALSE}
#knitr::opts_knit$set(root.dir = "/mnt/research/quantgen/projects/lopezcru/G2F_RESOURCES/Rcode")

library(ggplot2)
library(reshape2)
library(knitr)
library(ggpubr)
library(xtable)

source("../Tools/Functions.R")
dataW <- read.csv("../Data/OutputFiles/clean_EC_by_stage.csv", check.names=F)
pheno <- read.csv("../Data/OutputFiles/clean_pheno_raw.csv")

pheno <- pheno[pheno$year_loc %in% dataW$year_loc,]

pheno0 <- dataW[,1:4]
W0 <- as.matrix(dataW[,5:ncol(dataW)])
W <- scale(W0)
ZW <- scale(W0[match(pheno$year_loc,dataW$year_loc),])

pheno$year <- factor(as.character(pheno$year))
pheno$location <- factor(as.character(pheno$location))
pheno$year_loc <- factor(as.character(pheno$year_loc))

pheno0$year <- factor(as.character(pheno0$year))
pheno0$loc <- factor(as.character(pheno0$loc))
pheno0$year_loc <- factor(as.character(pheno0$year_loc))

```

## Leave-one-YL-out using models M1, M2a, and M2b

```{r echo=FALSE}
models1 <- c('M1'="YEAR+LOC+YL+G", 'M2a'="W1+G", 'M2b'="W2+G")
models2 <- c('M1'="YEAR+LOC+YL", 'M2a'="W1", 'M2b'="W2", 'M3a'="LOC+W1", 'M3b'="LOC+W2")
folds_lev <- levels(pheno$year_loc)
YHat1 <- matrix(NA, nrow=nrow(pheno),ncol=length(models1))
YHat2 <- matrix(NA, nrow=nrow(pheno0),ncol=length(models2))
colnames(YHat1) <- names(models1)
colnames(YHat2) <- names(models2)

for(ff in 1:length(folds_lev))
{
  for(mm in 1:length(models1))
  {
    filename <- paste0("../Output/run_LOO_YL/fm_YL_",folds_lev[ff],"_",names(models1)[mm],".RData")
    if(file.exists(filename)){
      load(filename)
      YHat1[indexNA,names(models1)[mm]] <- yHat[indexNA]
    }
  }
  for(mm in 1:length(models2))
  {
    filename <- paste0("../Output/run_LOO_YL_mean/fm_YL_",folds_lev[ff],"_",names(models2)[mm],".RData")
    if(file.exists(filename)){
      load(filename)
      YHat2[indexNA,names(models2)[mm]] <- yHat[indexNA]
    }
  }

}
YHat1 <- data.frame(YL=pheno$year_loc,yield=pheno$yield,YHat1)
YHat2 <- data.frame(YL=pheno0$year_loc,yield=pheno0$yield,YHat2)

# head(YHat1)
# head(YHat2)
```

### Using replicates
```{r fig.align = 'center', fig.width=5.1, fig.height=5.5}
for(k in 1:length(models1)){
  tmp <- ifelse(length(grep("a",names(models1)[k]))>0," (BRR)",
                ifelse(length(grep("b",names(models1)[k]))>0," (Bayes-C)",""))
  xlab <- paste0("Predicted ~ ", gsub("W1|W2","Wb",models1[k]), tmp)
  plot_conditional(YHat1[,names(models1)[k]],YHat1$yield, quantiles=0.5, xlab=xlab,
                   ylab="Observed",cex.axis=0.8, cex.point=0.5)
}

```

### Using year-location means
```{r fig.align = 'center', fig.width=5.1, fig.height=5.5}
for(k in 1:length(models2)){
  tmp <- ifelse(length(grep("a",names(models2)[k]))>0," (BRR)",
                ifelse(length(grep("b",names(models2)[k]))>0," (Bayes-C)",""))
  xlab <- paste0("Predicted ~ ", gsub("W1|W2","Wb",models2[k]), tmp)
  plot_conditional(YHat2[,names(models2)[k]],YHat2$yield, quantiles=0.5, xlab=xlab,
                   ylab="Observed", cex.axis=0.8)
}

```

## Leave-one-YEAR-out using models M1, M2a, M2b, M3a, and M3b

```{r echo=FALSE}
folds_lev <- levels(pheno0$year)
YHat3 <- matrix(NA, nrow=nrow(pheno0),ncol=length(models2))
colnames(YHat3) <- names(models2)

for(ff in 1:length(folds_lev))
{
  for(mm in 1:length(models2))
  {
    filename <- paste0("../Output/run_LOO_YEAR_mean/fm_YEAR_",folds_lev[ff],"_",names(models2)[mm],".RData")
    if(file.exists(filename)){
      load(filename)
      YHat3[indexNA,names(models2)[mm]] <- yHat[indexNA]
    }
  }
}
YHat3 <- data.frame(YEAR=pheno0$year, yield=pheno0$yield, YHat3)

# head(YHat3)
```

```{r fig.align = 'center', fig.width=5.1, fig.height=5.5}
for(k in 1:length(models2)){
  tmp <- ifelse(length(grep("a",names(models2)[k]))>0," (BRR)",
                ifelse(length(grep("b",names(models2)[k]))>0," (Bayes-C)",""))
  xlab <- paste0("Predicted ~ ", gsub("W1|W2","Wb",models2[k]), tmp)
  plot_conditional(YHat3[,names(models2)[k]],YHat3$yield, quantiles=0.5, xlab=xlab,
                   ylab="Observed", cex.axis=0.8)
}

```
