---
title: "Get simulated EC by stage"
output: pdf_document
---

```{r setup, echo=FALSE}
knitr::opts_knit$set(root.dir = "~/Dropbox/projects/G2F_RESOURCES/Rcode")

# Load functions
source('../Tools/Functions.R')
source('../Tools/APSIM_run_apsim.R')
library(lubridate)
library(pheatmap)
library(xtable)
library(knitr)
library(ggplot2)

```

```{r echo=FALSE}
# Load simulated EC data
dataEC <- read.csv("../Data/OutputFiles/simulated_EC_V1.csv", check.names = FALSE)

# Define phases
Stages <- c(Germ="Germination", Emer="Emergence", EndJuv="EndJuvenile",
            FlInit="FloralInitiation", FgLeaf="FlagLeaf",
          Flow="Flowering", StartGF="StartGrainFill",
          EndGF="EndGrainFill", Matu="Maturity", Harvest="HarvestRipe")

Phases <- c('Germ-Emer', 'Emer-FlInit', 'FlInit-FgLeaf', 'FgLeaf-Flow',
           'Flow-StartGF', 'StartGF-Matu')

keep_cols <- which(!colnames(dataEC) %in%
    c("year_loc","year","location","Clock.Today","Stage","WinterDate","Date","yield"))

cat("Processing", length(keep_cols),"ECs...\n")
out <- lapply(split(dataEC,dataEC$year_loc),function(x){
  x <- x[order(as.Date(x$Date), decreasing = FALSE),]
  if(sum(order(as.Date(x$Date)) != 1:nrow(x)) > 0) stop("Dates are not in correct order in year-loc ",x$year_loc[1])

  envmat <- matrix(NA, ncol = length(keep_cols), nrow = length(Phases))
  colnames(envmat) <- colnames(x)[keep_cols]
  for(k in 1:length(Phases)){
    s1 <- unlist(lapply(strsplit(Phases[k],"-"),function(x)x[1]))
    s2 <- unlist(lapply(strsplit(Phases[k],"-"),function(x)x[2]))
    n0 <- 1   # 1 day before the stage
    if(s2 == "Matu"){
      s2 <- c("EndGF","Matu","Harvest")
      n0 <- 0
    }
    index <- which(x$Stage == Stages[s1]):(max(which(x$Stage %in% Stages[s2]))-n0)
    envmat[k,] <- apply(x[index,keep_cols],2,mean)
  }
  envmat <- as.data.frame(envmat)
  #cat("Year-loc=",x$year_loc[1]," processed \n")
  as.data.frame(cbind(x[1,c("year_loc","year","location"),drop=T], yield=max(x$yield)*10, phase=Phases, envmat))
})

dataW <- do.call(rbind, out)
rownames(dataW) <- NULL
# dataW[1:10,1:10]
# dim(dataW)

dataW$phase <- factor(as.character(dataW$phase),levels=Phases)
dataW$year_loc <- factor(as.character(dataW$year_loc))

Fnames <- c("year_loc","year","location","yield")
data0 <- lapply(split(dataW, dataW$phase), function(x){
  tmp <- x[,-which(colnames(x) %in% c(Fnames,"phase"))]
  colnames(tmp) <- paste0(x$phase[1], '_', colnames(tmp))
  res=as.data.frame(cbind(x[, c(Fnames)], tmp))
  stopifnot(all(res$year_loc %in% levels(dataW$year_loc)))
  res[match(levels(dataW$year_loc),res$year_loc),]
})

W <- do.call(cbind,lapply(data0,function(x)as.matrix(x[,-c(1:4)])))
INFO <- data0[[1]][,1:4]

#head(W[,1:8])
#head(INFO[])

# Quality control ECs
mm <- apply(W,2,mean,na.rm=TRUE)
ss <- apply(W,2,sd,na.rm=TRUE)
cv <- ss/mm
drop <- which(ifelse(is.na(cv),TRUE,ifelse(abs(cv)<0.0001,TRUE,FALSE)))
if(length(drop)>0){   
  cat(length(drop),"of",ncol(W),"ECs with a |cv|<0.0001 were removed! \n")
  W <- W[,-drop]
}

# Remove NAs (keep columns with no un-observed values)
W <- W[,which(colSums(is.na(W)) == 0)]
if(any(colSums(is.na(W)) > 0)) stop("Some columns have NA values")
#dim(W)

dataW <- cbind(INFO,W)
head(dataW[,1:8])

write.csv(dataW, file = '../Data/OutputFiles/clean_EC_by_stage.csv', row.names=FALSE)

```

### Environmental covariates (EC) summary
```{r echo=FALSE, results='asis'}
phase <- unlist(lapply(strsplit(colnames(W),"_"),function(x)x[1])) # Phases

ec <- unlist(lapply(strsplit(colnames(W),"_"),function(x)x[2])) # Phases
ECs <- unique(ec)

out <- data.frame(Phase=paste0("P",1:length(Phases)),table(phase)[Phases])
colnames(out) <- c("Phase","Name","nEC")
kable(out)

```
### Hydric stress-related EC

```{r echo=FALSE, results = 'asis'}

tmp <- c(  
    'Eo'="Potential evapotransipration of the whole soil-plant system (mm)",
    'Eos'="Potential evaporation from soil surface (mm)",
    'Es'="Actual (realised) soil water evaporation (mm)",
    'Evap'="Evaporation (mm)",
    'ESW(i)'="Extractable soil water relative to LL15 (mm)",
    'Flow(i)'="Flow - Water moving up (mm)",
    'PAW(i)'="Plant available water SW-LL15 (mm/mm)"
)
out <- data.frame(Name=names(tmp),Description=as.vector(tmp))
print(xtable(out), type="latex", comment=FALSE)

```
$i$: soil profile ($i=1,...,10$) each 20 cm


\newpage

### Correlation between ECs
ESW across phases
```{r echo=FALSE, fig.align = 'center', fig.width=7, fig.height=6}
pp <- make_heatmap("ESW",W, cluster_rows=TRUE,cluster_cols=TRUE,
      fontsize=9,fontsize_row=5.9,fontsize_col=5.9, silent=TRUE)
print(pp)

```

\newpage

PAW across phases
```{r echo=FALSE, fig.align = 'center', fig.width=7, fig.height=6}
pp <- make_heatmap("PAW",W, cluster_rows=TRUE,cluster_cols=TRUE,
      fontsize=9,fontsize_row=5.9,fontsize_col=5.9, silent=TRUE)
print(pp)

```

\newpage

Flow across phases
```{r echo=FALSE, fig.align = 'center', fig.width=7, fig.height=6}
pp <- make_heatmap("Flow",W, cluster_rows=TRUE,cluster_cols=TRUE,
      fontsize=9,fontsize_row=5.9,fontsize_col=5.9, silent=TRUE)
print(pp)

```

\newpage

Eo, Eos, Es, Evap, Flow(i), ESW(i), and PAW(i), $i=1,4,7,10$
```{r echo=FALSE, fig.align = 'center', fig.width=7, fig.height=6}
pp <- make_heatmap(c("Eo","Eos","Es","Evap","Flow","ESW","PAW"),W,layer=c(1,4,7,10),
      cluster_rows=TRUE,cluster_cols=TRUE,
      fontsize=9,fontsize_row=3.3,fontsize_col=3.3, silent=TRUE)
print(pp)

```

\newpage

Principal Components decomposition of the covariance among ECs
```{r echo=FALSE, fig.align = 'center', fig.width=6.5, fig.height=4.9}
ec2 <- ec[]
ec2[grep("AboveGround", ec2)] <- "Biomass"
ec2[grep("Cover", ec2)] <- "Cover"
ec2[grep("SW", ec2)] <- "SW"
ec2[grep("ESW\\(", ec2)] <- "ESW"
ec2[grep("Flow\\(", ec2)] <- "Flow"
ec2[grep("FlowNO3", ec2)] <- "FlowNO3"
ec2[grep("LeachNO3", ec2)] <- "LeachNO3"
ec2[grep("Flux", ec2)] <- "Flux"
ec2[grep("PAW", ec2)] <- "PAW"
ec2[grep("Water", ec2)] <- "Water"
ec2[grep("Runoff", ec2)] <- "Runoff"
ec2[grep("Inf", ec2)] <- "Infiltration"
ec2[ec2 %in% c("SW","Water")] <- "Water"
ec2[ec2 %in% c("Eos","Es","Evap")] <- "Evaporation"
ec2[ec2 %in% c("T","LeachNO3","FlowNO3")] <- "Other"
#unique(ec2)

tmp <- cor(W)
EVD <- eigen(tmp)

expVar <- 100*EVD$values / sum(EVD$values)

dat <- data.frame(EVD$vectors[,1:2],EC_type=ec2)

ggplot(dat, aes(X1, X2, fill=EC_type)) + theme_bw() +
  geom_point(shape=21,size=1.8,color="gray20") +
  labs(x=paste0("PC1 (",round(expVar[1],2),"%)"), 
       y=paste0("PC2 (",round(expVar[2],2),"%)"), fill=NULL)

```


